"""
Mask-based selection strategies for block-sparse attention.

These strategies sit between two extremes:
  * Dense attention (no selection)
  * PBS / FlexPrefill (parameterised real kernels with built-in selection)

Each strategy implements the interface:

    result = strategy.select(q, k, v, block_size) -> SelectionResult
    overhead_est = strategy.t_overhead_ms(L)       -> float (ms estimate)

The ``run_block_sparse_attention`` helper executes attention using the block
mask generated by a strategy.

Overhead classes
----------------
O(1)     : GlobalSinkWindow, SqrtWindow
             T_select ≈ constant (tiny Python tensor-creation ops)
O(L·D)   : BlockKNormTopK, CoverageTarget
             T_select ≈ linear in L (single pass over K-norms)
O(r·L·D) : SampledAttentionTopK
             T_select ≈ r × O(L·D), where r is the number of sampled rows

Research question
-----------------
How does sequence length L affect the overhead-sparsity-accuracy tradeoff?

Key insight: PBS/Flex selection overhead grows with L (PBS ~0.1µs/token).
At short L (4K-8K), selection dominates the wall-time budget.
At long L (32K-64K+), selection amortises over large kernel savings.

This means there exists a length-dependent optimal selection strategy:
  - Short L → prefer O(1) strategies (trivial overhead, accept lower accuracy)
  - Long L  → can afford O(L·D) strategies for higher-quality masks
"""
from __future__ import annotations

import math
import time
from dataclasses import dataclass, field
from typing import Any

import torch
import torch.nn.functional as F

# Optional: flex_attention for real block-sparse kernel execution
try:
    from torch.nn.attention.flex_attention import BlockMask, flex_attention
    _HAS_FLEX = True
    _compiled_flex = torch.compile(flex_attention)
except Exception:
    _HAS_FLEX = False
    _compiled_flex = None


# ─── Result type ──────────────────────────────────────────────────────────────

@dataclass
class SelectionResult:
    """Output of ``strategy.select()``."""
    strategy_name: str
    block_mask: torch.Tensor   # [q_blocks, kv_blocks] bool ? True = compute this block pair
    sparsity:   float          # fraction of valid causal block pairs pruned  (1 ? active_frac)
    t_select_ms: float         # measured wall-clock selection time (ms)
    meta: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        self.block_mask = _ensure_causal_2d_mask(self.block_mask)
        self.sparsity = max(0.0, min(1.0, 1.0 - _causal_block_density(self.block_mask)))

    @property
    def active_fraction(self) -> float:
        return _causal_block_density(self.block_mask)

    @property
    def num_active(self) -> int:
        return int(self.block_mask.sum().item())


def _ensure_causal_2d_mask(block_mask: torch.Tensor) -> torch.Tensor:
    if block_mask.dim() == 2:
        return block_mask.to(dtype=torch.bool)
    if block_mask.dim() != 1:
        raise ValueError(f"expected 1D or 2D block mask, got shape {tuple(block_mask.shape)}")
    kv_keep = block_mask.to(dtype=torch.bool)
    num_blocks = int(kv_keep.numel())
    causal = torch.tril(torch.ones((num_blocks, num_blocks), dtype=torch.bool, device=kv_keep.device))
    return causal & kv_keep.unsqueeze(0)


def _causal_block_density(block_mask_2d: torch.Tensor) -> float:
    q_blocks, kv_blocks = block_mask_2d.shape
    diag = kv_blocks - q_blocks
    valid = torch.tril(torch.ones((q_blocks, kv_blocks), dtype=torch.bool, device=block_mask_2d.device), diagonal=diag)
    denom = int(valid.sum().item())
    if denom <= 0:
        return 1.0
    numer = int((block_mask_2d.to(torch.bool) & valid).sum().item())
    return numer / denom

def run_block_sparse_attention(
    q: torch.Tensor,  # [B, H, L, D]
    k: torch.Tensor,
    v: torch.Tensor,
    block_mask: torch.Tensor,  # [q_blocks, kv_blocks] bool
    block_size: int = 128,
    causal: bool = True,
) -> torch.Tensor:
    del causal
    B, H, L, D = q.shape
    block_mask_2d = _ensure_causal_2d_mask(block_mask)
    token_mask = block_mask_2d.repeat_interleave(block_size, dim=0).repeat_interleave(block_size, dim=1)
    token_mask = token_mask[:L, :L]
    bias = torch.where(
        token_mask.unsqueeze(0).unsqueeze(0),
        torch.zeros(1, 1, L, L, device=q.device, dtype=q.dtype),
        torch.full((1, 1, L, L), float('-inf'), device=q.device, dtype=q.dtype),
    )
    with torch.inference_mode():
        out = F.scaled_dot_product_attention(q, k, v, attn_mask=bias, is_causal=False)
    return out

def bool_mask_to_flex_block_mask(
    bool_mask_2d: torch.Tensor,
    L: int,
    block_size: int = 128,
) -> "BlockMask":
    """
    Convert a precomputed boolean [q_blocks, kv_blocks] block mask into a
    ``torch.nn.attention.flex_attention.BlockMask`` that ``flex_attention``
    (compiled) can use to skip inactive blocks.

    Approach
    --------
    * Splits the mask into "full" blocks (strictly below the causal diagonal —
      no token-level masking needed) and "partial" blocks (diagonal — requires
      a causal ``mask_mod`` at token level).
    * Builds each part in ``argsort``-ordered format expected by
      ``BlockMask.from_kv_blocks``:  active entries come first in each row.
    * All operations are O(q_blocks²) — avoids the O(token²) cost of
      ``create_block_mask``, making it viable at 128 K+ sequence lengths.

    Requires PyTorch ≥ 2.3 with ``torch.nn.attention.flex_attention``.
    """
    if not _HAS_FLEX:
        raise RuntimeError("flex_attention not available (requires PyTorch ? 2.3)")

    bm = _ensure_causal_2d_mask(bool_mask_2d)
    q_blocks, kv_blocks = bm.shape
    dev = bm.device

    lower = torch.tril(
        torch.ones(q_blocks, q_blocks, dtype=torch.bool, device=dev), diagonal=-1
    )
    diag = torch.eye(q_blocks, dtype=torch.bool, device=dev)

    full_mask    = bm & lower   # fully causal, no token-level mask needed
    partial_mask = bm & diag    # diagonal blocks: causal mask_mod applied

    def _to_ordered(mask_2d: torch.Tensor):
        """
        Convert dense [Q, KV] bool mask → argsort-ordered format.
        Returns (kv_num_blocks [1,1,Q], kv_indices [1,1,Q,KV]).
        Active blocks appear first in each row (argsort descending).
        """
        num  = mask_2d.sum(dim=-1, dtype=torch.int32)
        cols = torch.argsort(mask_2d.int(), dim=-1, descending=True, stable=True)
        return (
            num.reshape(1, 1, q_blocks),
            cols.to(torch.int32).reshape(1, 1, q_blocks, kv_blocks),
        )

    full_kv_num, full_kv_idx = _to_ordered(full_mask)
    part_kv_num, part_kv_idx = _to_ordered(partial_mask)

    def _causal_mod(b, h, q_idx, kv_idx):
        return q_idx >= kv_idx

    return BlockMask.from_kv_blocks(
        kv_num_blocks      = part_kv_num,
        kv_indices         = part_kv_idx,
        full_kv_num_blocks = full_kv_num,
        full_kv_indices    = full_kv_idx,
        BLOCK_SIZE         = block_size,
        mask_mod           = _causal_mod,
        seq_lengths        = (L, L),
    )


def run_block_sparse_attention_flex(
    q: torch.Tensor,
    k: torch.Tensor,
    v: torch.Tensor,
    block_mask_2d: torch.Tensor,   # [q_blocks, kv_blocks] bool
    block_size: int = 128,
) -> tuple[torch.Tensor, float]:
    """
    Run **actually sparse** attention using ``torch.compile(flex_attention)``
    with a ``BlockMask`` built from *block_mask_2d*.

    Returns
    -------
    output : torch.Tensor  [B, H, L, D]
    t_kernel_ms : float    — measured kernel wall-clock time (ms)

    Notes
    -----
    * The Triton kernel compiled by ``torch.compile(flex_attention)`` genuinely
      skips inactive blocks, achieving real O(active_frac × L²) compute.
    * Block-mask construction (``bool_mask_to_flex_block_mask``) is O(q_blocks²)
      and typically takes < 1 ms even at 128 K.
    * First call triggers JIT compilation (~1–2 s); use warmup before timing.
    """
    if not _HAS_FLEX:
        raise RuntimeError("flex_attention not available (requires PyTorch ≥ 2.3)")

    B, H, L, D = q.shape
    flex_bm = bool_mask_to_flex_block_mask(block_mask_2d, L, block_size)

    start = torch.cuda.Event(enable_timing=True)
    end   = torch.cuda.Event(enable_timing=True)

    with torch.inference_mode():
        start.record()
        out = _compiled_flex(q, k, v, block_mask=flex_bm)
        end.record()
    torch.cuda.synchronize()

    return out, start.elapsed_time(end)


# ─── Base class ───────────────────────────────────────────────────────────────

class SelectionStrategy:
    """Abstract base for all selection strategies."""

    name: str = "base"

    def select(
        self,
        q: torch.Tensor,
        k: torch.Tensor,
        v: torch.Tensor,
        block_size: int = 128,
    ) -> SelectionResult:
        raise NotImplementedError

    def t_overhead_ms(self, L: int) -> float:
        """Analytical estimate of selection time in ms."""
        return 0.0


# ─── O(1) strategies ──────────────────────────────────────────────────────────

class GlobalSinkWindow(SelectionStrategy):
    """
    Global sink tokens + local sliding window.

    Keeps:
      * First ``sink_blocks`` blocks (global attention — sink tokens)
      * Last ``window_blocks`` blocks  (local context)
      * Always the block containing the query (causal trailing block)

    T_select ≈ O(1): just index arithmetic, no tensor arithmetic over K/V.

    Research relevance: A classic structural prior.  Tests whether the
    "global-sink + local" structure suffices at each L without any data-driven
    cost.
    """
    name = "GlobalSinkWindow"

    def __init__(self, sink_blocks: int = 2, window_blocks: int = 4):
        self.sink_blocks   = sink_blocks
        self.window_blocks = window_blocks

    def select(
        self,
        q: torch.Tensor,
        k: torch.Tensor,
        v: torch.Tensor,
        block_size: int = 128,
    ) -> SelectionResult:
        L = q.shape[2]
        num_blocks = max(1, L // block_size)

        t0 = time.perf_counter()

        mask = torch.zeros(num_blocks, dtype=torch.bool, device=q.device)
        # Global sink
        sink_end = min(self.sink_blocks, num_blocks)
        mask[:sink_end] = True
        # Local window (last N blocks)
        win_start = max(sink_end, num_blocks - self.window_blocks)
        mask[win_start:] = True

        t_select_ms = (time.perf_counter() - t0) * 1e3

        active = int(mask.sum().item())
        sparsity = 1.0 - active / num_blocks
        return SelectionResult(
            strategy_name=self.name,
            block_mask=mask,
            sparsity=max(0.0, sparsity),
            t_select_ms=t_select_ms,
            meta={"sink_blocks": self.sink_blocks, "window_blocks": self.window_blocks},
        )

    def t_overhead_ms(self, L: int) -> float:
        # Index ops: constant regardless of L
        return 0.005  # ~5 µs


class SqrtWindow(SelectionStrategy):
    """
    Local window whose size scales as sqrt(L) tokens.

    Keeps the last ``ceil(sqrt(L) / block_size)`` key blocks plus the first
    ``sink_blocks`` global-attention blocks.

    Motivation: sqrt(L) is a theoretically motivated budget that grows
    sub-linearly with context — it keeps the active fraction low at large L
    while still covering O(sqrt(L)) context.

    T_select ≈ O(1): one math.sqrt call.
    """
    name = "SqrtWindow"

    def __init__(self, sink_blocks: int = 1):
        self.sink_blocks = sink_blocks

    def select(
        self,
        q: torch.Tensor,
        k: torch.Tensor,
        v: torch.Tensor,
        block_size: int = 128,
    ) -> SelectionResult:
        L = q.shape[2]
        num_blocks = max(1, L // block_size)

        t0 = time.perf_counter()

        window_tokens = max(block_size, math.ceil(math.sqrt(L)))
        window_blocks = max(1, math.ceil(window_tokens / block_size))
        window_blocks = min(window_blocks, num_blocks)

        mask = torch.zeros(num_blocks, dtype=torch.bool, device=q.device)
        # Global sink
        sink_end = min(self.sink_blocks, num_blocks)
        mask[:sink_end] = True
        # Sqrt window
        win_start = max(sink_end, num_blocks - window_blocks)
        mask[win_start:] = True

        t_select_ms = (time.perf_counter() - t0) * 1e3

        active = int(mask.sum().item())
        sparsity = 1.0 - active / num_blocks
        return SelectionResult(
            strategy_name=self.name,
            block_mask=mask,
            sparsity=max(0.0, sparsity),
            t_select_ms=t_select_ms,
            meta={"window_blocks": window_blocks, "window_tokens": window_tokens},
        )

    def t_overhead_ms(self, L: int) -> float:
        return 0.005  # constant


# ─── O(L·D) strategies ────────────────────────────────────────────────────────

class BlockKNormTopK(SelectionStrategy):
    """
    Select top-f fraction of key blocks by L2-norm of their tokens.

    Algorithm:
      1. Compute K-norm per token: ||k_i||₂  — O(L·D)
      2. Average over batch and heads
      3. Sum norms within each block                — O(L)
      4. Select top (f × num_blocks) blocks by norm score

    Rationale: blocks with high K-norm correspond to high-attention tokens
    (tokens that many queries attend to).  This is a data-driven selection
    with O(L·D) overhead — more informative than SqrtWindow but more costly.

    Length effect: at short L, cost is small in absolute terms; at long L,
    the O(L·D) pass becomes the bottleneck.  This directly tests when O(L·D)
    overhead is worth paying relative to the kernel savings.
    """
    name = "BlockKNormTopK"

    def __init__(self, topk_frac: float = 0.25, sink_blocks: int = 1):
        self.topk_frac   = topk_frac
        self.sink_blocks = sink_blocks

    def select(
        self,
        q: torch.Tensor,
        k: torch.Tensor,
        v: torch.Tensor,
        block_size: int = 128,
    ) -> SelectionResult:
        B, H, L, D = k.shape
        num_blocks = max(1, L // block_size)
        trim = num_blocks * block_size  # aligned length

        t0 = time.perf_counter()

        with torch.inference_mode():
            # L2-norm per token, averaged over batch & heads
            k_norms = k[..., :trim, :].float().norm(dim=-1)  # [B, H, trim]
            k_norms_mean = k_norms.mean(dim=(0, 1))           # [trim]
            # Sum within blocks
            block_norms = k_norms_mean.reshape(num_blocks, block_size).sum(-1)  # [num_blocks]

            # Always keep sink blocks
            sink_end = min(self.sink_blocks, num_blocks)
            # Number of dynamic top-k blocks (excluding sinks)
            budget = max(1, round(num_blocks * self.topk_frac))
            budget = max(0, budget - sink_end)

            if budget > 0 and num_blocks > sink_end:
                # Mask sinks from competition so we don't double-count
                block_norms[:sink_end] = float("-inf")
                _, dyn_idx = block_norms.topk(min(budget, num_blocks - sink_end))
                mask = torch.zeros(num_blocks, dtype=torch.bool, device=k.device)
                mask[:sink_end] = True
                mask[dyn_idx] = True
            else:
                mask = torch.zeros(num_blocks, dtype=torch.bool, device=k.device)
                mask[:sink_end] = True

        torch.cuda.synchronize()
        t_select_ms = (time.perf_counter() - t0) * 1e3

        active   = int(mask.sum().item())
        sparsity = 1.0 - active / num_blocks
        return SelectionResult(
            strategy_name=self.name,
            block_mask=mask,
            sparsity=max(0.0, sparsity),
            t_select_ms=t_select_ms,
            meta={"topk_frac": self.topk_frac, "budget": budget},
        )

    def t_overhead_ms(self, L: int) -> float:
        # Empirically ~0.005 ms/token for norm computation on A800 (BF16)
        # t ≈ C_norm × L, where C_norm ≈ 5 ns/token
        return 0.005e-3 * L   # ms


class CoverageTarget(SelectionStrategy):
    """
    Select the minimum set of blocks whose cumulative K-norm mass covers
    ``target_coverage`` fraction of the total key mass.

    Algorithm:
      1. Compute block-level K-norms (same as BlockKNormTopK)
      2. Sort blocks by norm descending
      3. Greedily add blocks until cumulative mass ≥ target_coverage × total_mass

    This is an adaptive budget: high-sparsity inputs need fewer blocks.
    The selection budget varies with actual input sparsity, unlike TopK which
    uses a fixed fraction.

    Length effect: the coverage threshold determines how much of the key mass
    is captured.  At long L with clustered attention, fewer blocks cover the
    same mass → more aggressive pruning without accuracy loss.
    """
    name = "CoverageTarget"

    def __init__(self, target_coverage: float = 0.90, sink_blocks: int = 1):
        self.target_coverage = target_coverage
        self.sink_blocks     = sink_blocks

    def select(
        self,
        q: torch.Tensor,
        k: torch.Tensor,
        v: torch.Tensor,
        block_size: int = 128,
    ) -> SelectionResult:
        B, H, L, D = k.shape
        num_blocks = max(1, L // block_size)
        trim = num_blocks * block_size

        t0 = time.perf_counter()

        with torch.inference_mode():
            k_norms = k[..., :trim, :].float().norm(dim=-1)
            k_norms_mean = k_norms.mean(dim=(0, 1))
            block_norms = k_norms_mean.reshape(num_blocks, block_size).sum(-1)

            total_mass = block_norms.sum().item()
            if total_mass < 1e-12:
                # Degenerate: keep all
                mask = torch.ones(num_blocks, dtype=torch.bool, device=k.device)
            else:
                # Sort descending
                sorted_idx = block_norms.argsort(descending=True)
                cum = 0.0
                selected = []
                for i in sorted_idx.tolist():
                    selected.append(i)
                    cum += block_norms[i].item()
                    if cum >= self.target_coverage * total_mass:
                        break
                # Always include sink blocks
                for s in range(min(self.sink_blocks, num_blocks)):
                    if s not in selected:
                        selected.append(s)
                mask = torch.zeros(num_blocks, dtype=torch.bool, device=k.device)
                mask[selected] = True

        torch.cuda.synchronize()
        t_select_ms = (time.perf_counter() - t0) * 1e3

        active   = int(mask.sum().item())
        sparsity = 1.0 - active / num_blocks
        return SelectionResult(
            strategy_name=self.name,
            block_mask=mask,
            sparsity=max(0.0, sparsity),
            t_select_ms=t_select_ms,
            meta={
                "target_coverage": self.target_coverage,
                "actual_coverage": min(1.0, active / num_blocks),
            },
        )

    def t_overhead_ms(self, L: int) -> float:
        # Sort is O(num_blocks × log(num_blocks)), norm is O(L)
        # Dominant: O(L), similar to BlockKNormTopK
        return 0.006e-3 * L   # slightly more than KNorm due to sort


# ─── O(r·L·D) strategies ──────────────────────────────────────────────────────

class SampledAttentionTopK(SelectionStrategy):
    """
    Select key blocks by attention mass estimated from ``sample_rows`` random
    query positions.

    Algorithm (per sampled query row i):
      1. Compute attention scores: q_i · K^T / sqrt(D)  — O(L·D)
      2. Softmax over the causal prefix
      3. Sum attention weights within each key block
      4. Accumulate block-level importance across sampled rows

    Final block mask: top ``topk_frac`` fraction of blocks by accumulated mass.

    Advantages over K-norm:
      * Attention-mass captures *query-specific* importance, not just key magnitude
      * ``r`` controls the overhead-quality tradeoff: r=1 is cheap, r=32 is good

    Length effect: r is kept FIXED regardless of L.  Total overhead = r × O(L·D).
    At short L: r×O(L·D) is fast in absolute terms.
    At long L:  r×O(L·D) becomes expensive (PBS-comparable for r~16).
    This makes r the key parameter for the length-crossover analysis.
    """
    name = "SampledAttentionTopK"

    def __init__(
        self,
        sample_rows: int  = 16,
        topk_frac:   float = 0.25,
        sink_blocks: int  = 1,
        seed:        int   = 0,
    ):
        self.sample_rows = sample_rows
        self.topk_frac   = topk_frac
        self.sink_blocks = sink_blocks
        self.seed        = seed

    def select(
        self,
        q: torch.Tensor,
        k: torch.Tensor,
        v: torch.Tensor,
        block_size: int = 128,
    ) -> SelectionResult:
        B, H, L, D = q.shape
        num_blocks = max(1, L // block_size)
        scale = math.sqrt(D)

        t0 = time.perf_counter()

        with torch.inference_mode():
            rng = torch.Generator(device=q.device)
            rng.manual_seed(self.seed)

            # Sample from the second half of the sequence (non-trivial queries)
            min_start = min(block_size, L // 4)
            n_sample   = min(self.sample_rows, L - min_start)
            if n_sample <= 0:
                n_sample = 1
                min_start = 0
            sample_idx = torch.randint(min_start, L, (n_sample,),
                                       generator=rng, device=q.device)

            block_mass = torch.zeros(num_blocks, device=q.device, dtype=torch.float32)

            for ri in sample_idx.tolist():
                ri = int(ri)
                qi  = q[:, :, ri:ri+1, :]          # [B, H, 1, D]
                ki  = k[:, :, :ri+1, :]              # [B, H, ri+1, D]
                scores = (qi @ ki.transpose(-1, -2)).squeeze(2) / scale  # [B, H, ri+1]
                attn   = torch.softmax(scores.float(), dim=-1)            # [B, H, ri+1]

                ctx_len = ri + 1
                ctx_blocks = ctx_len // block_size
                if ctx_blocks == 0:
                    continue
                trim = ctx_blocks * block_size
                bm = (attn[..., :trim]
                      .reshape(B, H, ctx_blocks, block_size)
                      .sum(-1)
                      .mean(dim=(0, 1)))   # [ctx_blocks]
                block_mass[:ctx_blocks] += bm

            block_mass = block_mass / max(n_sample, 1)

            # Always keep sink blocks
            sink_end = min(self.sink_blocks, num_blocks)
            budget   = max(1, round(num_blocks * self.topk_frac))

            if num_blocks > sink_end:
                block_mass[:sink_end] = float("inf")  # force sinks into top-k
                _, top_idx = block_mass.topk(min(budget, num_blocks))
                mask = torch.zeros(num_blocks, dtype=torch.bool, device=q.device)
                mask[top_idx] = True
            else:
                mask = torch.ones(num_blocks, dtype=torch.bool, device=q.device)

        torch.cuda.synchronize()
        t_select_ms = (time.perf_counter() - t0) * 1e3

        active   = int(mask.sum().item())
        sparsity = 1.0 - active / num_blocks
        return SelectionResult(
            strategy_name=self.name,
            block_mask=mask,
            sparsity=max(0.0, sparsity),
            t_select_ms=t_select_ms,
            meta={"sample_rows": self.sample_rows, "topk_frac": self.topk_frac},
        )

    def t_overhead_ms(self, L: int) -> float:
        # r attention score vectors of length L each: O(r * L * D)
        # On A800 BF16: ~0.01 ms per (L × D = 4096 × 128) matmul
        # Approximation: 0.01 ms × r × (L / 4096)
        return 0.01 * self.sample_rows * (L / 4096)


# ─── Long-sequence specialised strategies ────────────────────────────────────
#
# At long L (32K–128K), three issues dominate:
#   1. PBS selection overhead grows linearly and may exceed kernel savings.
#   2. Attention concentrates on fewer tokens → high-quality selection matters more.
#   3. Memory bandwidth for K/V is the bottleneck → aggressive pruning pays off.
#
# The strategies below are designed with the long-L regime in mind.

class DecayedWindowSink(SelectionStrategy):
    """
    Exponentially decaying window: heavier weight on recent blocks, lighter on
    distant past.  Unlike a hard window cut-off, this retains a small "long-
    range tail" of periodic strided blocks to capture rare long-distance
    dependencies.

    Algorithm (O(1) — pure index arithmetic):
      1. Always keep first ``sink_blocks`` blocks (global sinks).
      2. Keep the last ``window_blocks`` blocks (local context).
      3. Sample ``stride_blocks`` strided blocks from the middle region
         with spacing proportional to L / stride_blocks.

    Motivation for long L:
      At 64K–128K tokens the local window dominates but strided "memory" blocks
      prevent catastrophic forgetting of mid-range patterns.  Selection overhead
      is still O(1) — zero tensor arithmetic.

    Overhead: O(1), ~5 µs.
    """
    name = "DecayedWindowSink"

    def __init__(
        self,
        sink_blocks:   int = 2,
        window_blocks: int = 8,
        stride_blocks: int = 4,
    ):
        self.sink_blocks   = sink_blocks
        self.window_blocks = window_blocks
        self.stride_blocks = stride_blocks

    def select(
        self,
        q: torch.Tensor,
        k: torch.Tensor,
        v: torch.Tensor,
        block_size: int = 128,
    ) -> SelectionResult:
        L = q.shape[2]
        num_blocks = max(1, L // block_size)

        t0 = time.perf_counter()

        mask = torch.zeros(num_blocks, dtype=torch.bool, device=q.device)

        # 1. Global sinks
        sink_end = min(self.sink_blocks, num_blocks)
        mask[:sink_end] = True

        # 2. Local window (tail)
        win_start = max(sink_end, num_blocks - self.window_blocks)
        mask[win_start:] = True

        # 3. Strided "memory" blocks from the middle region
        mid_start = sink_end
        mid_end   = win_start
        if mid_end > mid_start and self.stride_blocks > 0:
            mid_len = mid_end - mid_start
            step = max(1, mid_len // self.stride_blocks)
            for i in range(mid_start, mid_end, step):
                mask[i] = True

        t_select_ms = (time.perf_counter() - t0) * 1e3

        active   = int(mask.sum().item())
        sparsity = 1.0 - active / num_blocks
        return SelectionResult(
            strategy_name=self.name,
            block_mask=mask,
            sparsity=max(0.0, sparsity),
            t_select_ms=t_select_ms,
            meta={
                "sink_blocks":   self.sink_blocks,
                "window_blocks": self.window_blocks,
                "stride_blocks": self.stride_blocks,
            },
        )

    def t_overhead_ms(self, L: int) -> float:
        return 0.005  # constant O(1)


class HierarchicalKNorm(SelectionStrategy):
    """
    Two-level coarse-to-fine K-norm selection — faster than flat BlockKNormTopK
    at very long sequences.

    Algorithm (O(L·D) but with a lower constant than flat TopK):
      Stage 1 — Coarse:  Group blocks into ``coarse_factor`` super-blocks.
                          Compute average block-norm per super-block.  Select
                          top ``coarse_keep_frac`` super-blocks.  O(L·D / coarse_factor)
      Stage 2 — Fine:    Within each kept super-block, select top
                          ``fine_keep_frac`` blocks by block-norm.
                          O(selected_blocks × block_size × D)

    Why this beats flat TopK at long L:
      Flat TopK requires sorting all num_blocks entries (O(B log B) where B=L/128).
      Hierarchical reduces the sort domain by coarse_factor at each stage, cutting
      constant factors significantly at B ≥ 256 (L ≥ 32K).

    Parameters
    ----------
    coarse_factor  : number of blocks per super-block (default 8)
    coarse_keep    : fraction of super-blocks to keep in stage 1
    fine_keep      : fraction of blocks to keep within a super-block in stage 2
    sink_blocks    : always-kept leading blocks (global sinks)
    """
    name = "HierarchicalKNorm"

    def __init__(
        self,
        coarse_factor:  int   = 8,
        coarse_keep:    float = 0.50,
        fine_keep:      float = 0.40,
        sink_blocks:    int   = 1,
    ):
        self.coarse_factor = coarse_factor
        self.coarse_keep   = coarse_keep
        self.fine_keep     = fine_keep
        self.sink_blocks   = sink_blocks

    def select(
        self,
        q: torch.Tensor,
        k: torch.Tensor,
        v: torch.Tensor,
        block_size: int = 128,
    ) -> SelectionResult:
        B, H, L, D = k.shape
        num_blocks = max(1, L // block_size)
        trim = num_blocks * block_size

        t0 = time.perf_counter()

        with torch.inference_mode():
            # Block-level K norms  [num_blocks]
            k_norms = k[..., :trim, :].float().norm(dim=-1)       # [B, H, trim]
            k_norms_mean = k_norms.mean(dim=(0, 1))                # [trim]
            block_norms = k_norms_mean.reshape(num_blocks, block_size).sum(-1)

            sink_end = min(self.sink_blocks, num_blocks)

            # Stage 1: coarse super-block selection
            n_super = max(1, num_blocks // self.coarse_factor)
            # Pad if needed
            pad = n_super * self.coarse_factor - num_blocks
            padded = torch.cat([
                block_norms,
                block_norms.new_zeros(pad)
            ]) if pad > 0 else block_norms
            super_norms = padded.reshape(n_super, self.coarse_factor).sum(-1)

            n_keep_super = max(1, round(n_super * self.coarse_keep))
            _, top_super = super_norms.topk(min(n_keep_super, n_super))
            top_super_set = set(top_super.tolist())

            # Stage 2: fine block selection within kept super-blocks
            mask = torch.zeros(num_blocks, dtype=torch.bool, device=k.device)
            mask[:sink_end] = True

            for si in top_super_set:
                start = si * self.coarse_factor
                end   = min(start + self.coarse_factor, num_blocks)
                if start >= end:
                    continue
                sub_norms = block_norms[start:end]
                n_fine = max(1, round((end - start) * self.fine_keep))
                _, fine_idx = sub_norms.topk(min(n_fine, end - start))
                mask[start + fine_idx] = True

        torch.cuda.synchronize()
        t_select_ms = (time.perf_counter() - t0) * 1e3

        active   = int(mask.sum().item())
        sparsity = 1.0 - active / num_blocks
        return SelectionResult(
            strategy_name=self.name,
            block_mask=mask,
            sparsity=max(0.0, sparsity),
            t_select_ms=t_select_ms,
            meta={
                "coarse_factor": self.coarse_factor,
                "coarse_keep":   self.coarse_keep,
                "fine_keep":     self.fine_keep,
                "n_super":       n_super,
            },
        )

    def t_overhead_ms(self, L: int) -> float:
        # Stage 1: O(L/D × coarse_factor norms) — lower constant than flat
        # Stage 2: O(kept_frac × L × D)
        # Net: similar to KNorm but with smaller sort overhead
        return 4e-6 * L + 0.04   # ~4 ns/token + 40 µs launch


class AdaptiveCoverage(SelectionStrategy):
    """
    Coverage-target selection with a length-adaptive coverage threshold.

    Motivation:
      At short L, attention mass is spread over many blocks — high coverage
      is needed to avoid accuracy loss.
      At long L, attention concentrates → the same accuracy can be maintained
      with much lower coverage (fewer blocks selected).

    The coverage threshold scales with log(L):
      coverage(L) = base_coverage × (1 - alpha × log2(L / L_ref))
      clipped to [min_coverage, base_coverage].

    This captures the empirical observation that Flex's gamma selector
    effectively operates at a lower active fraction at long L.

    Overhead: O(L·D) — same as CoverageTarget.
    """
    name = "AdaptiveCoverage"

    def __init__(
        self,
        base_coverage: float = 0.90,
        min_coverage:  float = 0.50,
        alpha:         float = 0.08,
        l_ref:         int   = 4_096,
        sink_blocks:   int   = 1,
    ):
        self.base_coverage = base_coverage
        self.min_coverage  = min_coverage
        self.alpha         = alpha
        self.l_ref         = l_ref
        self.sink_blocks   = sink_blocks

    def _coverage(self, L: int) -> float:
        reduction = self.alpha * math.log2(max(1, L / self.l_ref))
        return max(self.min_coverage, self.base_coverage - reduction)

    def select(
        self,
        q: torch.Tensor,
        k: torch.Tensor,
        v: torch.Tensor,
        block_size: int = 128,
    ) -> SelectionResult:
        B, H, L, D = k.shape
        num_blocks = max(1, L // block_size)
        trim = num_blocks * block_size
        target = self._coverage(L)

        t0 = time.perf_counter()

        with torch.inference_mode():
            k_norms = k[..., :trim, :].float().norm(dim=-1)
            k_norms_mean = k_norms.mean(dim=(0, 1))
            block_norms = k_norms_mean.reshape(num_blocks, block_size).sum(-1)

            total_mass = block_norms.sum().item()
            if total_mass < 1e-12:
                mask = torch.ones(num_blocks, dtype=torch.bool, device=k.device)
            else:
                sorted_idx = block_norms.argsort(descending=True)
                cum = 0.0
                selected = []
                for i in sorted_idx.tolist():
                    selected.append(i)
                    cum += block_norms[i].item()
                    if cum >= target * total_mass:
                        break
                for s in range(min(self.sink_blocks, num_blocks)):
                    if s not in selected:
                        selected.append(s)
                mask = torch.zeros(num_blocks, dtype=torch.bool, device=k.device)
                mask[selected] = True

        torch.cuda.synchronize()
        t_select_ms = (time.perf_counter() - t0) * 1e3

        active   = int(mask.sum().item())
        sparsity = 1.0 - active / num_blocks
        return SelectionResult(
            strategy_name=self.name,
            block_mask=mask,
            sparsity=max(0.0, sparsity),
            t_select_ms=t_select_ms,
            meta={
                "target_coverage":  round(target, 3),
                "base_coverage":    self.base_coverage,
                "actual_coverage":  round(active / num_blocks, 3),
            },
        )

    def t_overhead_ms(self, L: int) -> float:
        return 6e-6 * L + 0.05   # O(L) norm + sort


# ─── Strategy registry ────────────────────────────────────────────────────────

def default_strategies(block_size: int = 128) -> list[SelectionStrategy]:
    """Return a representative set of strategies for the sweep."""
    return [
        # O(1) — general ————————————————————————————
        GlobalSinkWindow(sink_blocks=2, window_blocks=4),
        GlobalSinkWindow(sink_blocks=2, window_blocks=8),
        SqrtWindow(sink_blocks=1),
        # O(1) — long-sequence specialised ————————————
        DecayedWindowSink(sink_blocks=2, window_blocks=8,  stride_blocks=4),
        DecayedWindowSink(sink_blocks=2, window_blocks=16, stride_blocks=8),
        # O(L·D) — general ——————————————————————————
        BlockKNormTopK(topk_frac=0.20),
        BlockKNormTopK(topk_frac=0.30),
        CoverageTarget(target_coverage=0.85),
        CoverageTarget(target_coverage=0.95),
        # O(L·D) — long-sequence specialised ————————
        HierarchicalKNorm(coarse_factor=8, coarse_keep=0.50, fine_keep=0.40),
        HierarchicalKNorm(coarse_factor=4, coarse_keep=0.40, fine_keep=0.50),
        AdaptiveCoverage(base_coverage=0.90, min_coverage=0.50, alpha=0.08),
        AdaptiveCoverage(base_coverage=0.85, min_coverage=0.40, alpha=0.10),
        # O(r·L·D) ——————————————————————————————————
        SampledAttentionTopK(sample_rows=4,  topk_frac=0.25),
        SampledAttentionTopK(sample_rows=16, topk_frac=0.25),
        SampledAttentionTopK(sample_rows=32, topk_frac=0.25),
    ]


def long_sequence_strategies(block_size: int = 128) -> list[SelectionStrategy]:
    """Return strategies optimised for L ≥ 32K."""
    return [
        # O(1): strided window with more long-range coverage
        DecayedWindowSink(sink_blocks=2, window_blocks=8,  stride_blocks=4),
        DecayedWindowSink(sink_blocks=2, window_blocks=16, stride_blocks=8),
        DecayedWindowSink(sink_blocks=4, window_blocks=16, stride_blocks=8),
        # O(L·D): hierarchical — fast for large B
        HierarchicalKNorm(coarse_factor=8,  coarse_keep=0.50, fine_keep=0.40),
        HierarchicalKNorm(coarse_factor=16, coarse_keep=0.40, fine_keep=0.50),
        # O(L·D): adaptive coverage that self-calibrates to input concentration
        AdaptiveCoverage(base_coverage=0.90, min_coverage=0.50, alpha=0.08),
        AdaptiveCoverage(base_coverage=0.85, min_coverage=0.40, alpha=0.10),
        AdaptiveCoverage(base_coverage=0.80, min_coverage=0.35, alpha=0.12),
        # O(r·L·D): sampled — fewer rows acceptable at long L (concentration helps)
        SampledAttentionTopK(sample_rows=4,  topk_frac=0.20),
        SampledAttentionTopK(sample_rows=8,  topk_frac=0.20),
    ]


def overhead_class(strategy: SelectionStrategy) -> str:
    """Return the overhead complexity class of a strategy."""
    if isinstance(strategy, (GlobalSinkWindow, SqrtWindow, DecayedWindowSink)):
        return "O(1)"
    if isinstance(strategy, (BlockKNormTopK, CoverageTarget,
                              HierarchicalKNorm, AdaptiveCoverage)):
        return "O(L·D)"
    if isinstance(strategy, SampledAttentionTopK):
        return f"O({strategy.sample_rows}·L·D)"
    return "O(?)"
